name = "lab7"
uuid = "2db93611-1c61-4cb5-a248-74439fd8ec90"
authors = ["Eric Ford <ebf11@psu.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
ParallelDataTransfer = "2dcacdae-9679-587a-88bb-8b444fb7085b"
ParallelUtilities = "fad6cfc8-4f83-11e9-06cc-151124046ad0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SlurmClusterManager = "c82cd089-7bf7-41d7-976b-6b5d413cbe0a"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
